spring:
  application:
    name: customer-default

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

spring:    
  boot:
    admin:
      client:
        url: http://localhost:8087

management:
  endpoints:
    web:
      exposure:
        include: "*"

