spring:
  application:
    name: CUSTOMER

  boot:
    admin:
      client:
        url: http://localhost:8087

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
